# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from gui.EmitterPatternDialog import Ui_EmitterPatternDialog
from gui.CustomQtObjects import PlainTextEdit


class Ui_TestSetupDialog(object):
    
    def __init__(self, test_setup, emitter_pattern):
        
        # Keep track of the test setup
        self.__test_setup = test_setup
        
        # Keep track of the emitter pattern
        self.__emitter_pattern = emitter_pattern
    
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(751, 639)
        self.testSetupLabel = QtWidgets.QLabel(Dialog)
        self.testSetupLabel.setGeometry(QtCore.QRect(30, 0, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.testSetupLabel.setFont(font)
        self.testSetupLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.testSetupLabel.setObjectName("testSetupLabel")
        self.conditionsLabel = QtWidgets.QLabel(Dialog)
        self.conditionsLabel.setGeometry(QtCore.QRect(10, 570, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.conditionsLabel.setFont(font)
        self.conditionsLabel.setObjectName("conditionsLabel")
        self.conditionsTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.conditionsTextEdit.setGeometry(QtCore.QRect(90, 570, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.conditionsTextEdit.setFont(font)
        self.conditionsTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.conditionsTextEdit.setObjectName("conditionsTextEdit")
        self.controlSettingsLabel = QtWidgets.QLabel(Dialog)
        self.controlSettingsLabel.setGeometry(QtCore.QRect(46, 70, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.controlSettingsLabel.setFont(font)
        self.controlSettingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlSettingsLabel.setObjectName("controlSettingsLabel")
        self.externalSettingsLabel = QtWidgets.QLabel(Dialog)
        self.externalSettingsLabel.setGeometry(QtCore.QRect(40, 350, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.externalSettingsLabel.setFont(font)
        self.externalSettingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.externalSettingsLabel.setObjectName("externalSettingsLabel")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 380, 191, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.VCSELBiasLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.VCSELBiasLabel.setFont(font)
        self.VCSELBiasLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VCSELBiasLabel.setObjectName("VCSELBiasLabel")
        self.verticalLayout_3.addWidget(self.VCSELBiasLabel)
        self.laserWavelengthLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.laserWavelengthLabel.setFont(font)
        self.laserWavelengthLabel.setObjectName("laserWavelengthLabel")
        self.verticalLayout_3.addWidget(self.laserWavelengthLabel)
        self.laserPowerLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.laserPowerLabel.setFont(font)
        self.laserPowerLabel.setObjectName("laserPowerLabel")
        self.verticalLayout_3.addWidget(self.laserPowerLabel)
        self.laserBandwidthLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.laserBandwidthLabel.setFont(font)
        self.laserBandwidthLabel.setObjectName("laserBandwidthLabel")
        self.verticalLayout_3.addWidget(self.laserBandwidthLabel)
        self.fiberTypeLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiberTypeLabel.setFont(font)
        self.fiberTypeLabel.setObjectName("fiberTypeLabel")
        self.verticalLayout_3.addWidget(self.fiberTypeLabel)
        self.otherEquipmentLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.otherEquipmentLabel.setFont(font)
        self.otherEquipmentLabel.setObjectName("otherEquipmentLabel")
        self.verticalLayout_3.addWidget(self.otherEquipmentLabel)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(230, 380, 131, 171))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.VCSELBiasTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.VCSELBiasTextEdit.setFont(font)
        self.VCSELBiasTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.VCSELBiasTextEdit.setObjectName("VCSELBiasTextEdit")
        self.verticalLayout_5.addWidget(self.VCSELBiasTextEdit)
        self.laserWavelengthTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.laserWavelengthTextEdit.setFont(font)
        self.laserWavelengthTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.laserWavelengthTextEdit.setObjectName("laserWavelengthTextEdit")
        self.verticalLayout_5.addWidget(self.laserWavelengthTextEdit)
        self.laserPowerTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.laserPowerTextEdit.setFont(font)
        self.laserPowerTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.laserPowerTextEdit.setObjectName("laserPowerTextEdit")
        self.verticalLayout_5.addWidget(self.laserPowerTextEdit)
        self.laserBandwidthTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.laserBandwidthTextEdit.setFont(font)
        self.laserBandwidthTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.laserBandwidthTextEdit.setObjectName("laserBandwidthTextEdit")
        self.verticalLayout_5.addWidget(self.laserBandwidthTextEdit)
        self.fiberTypeTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fiberTypeTextEdit.setFont(font)
        self.fiberTypeTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fiberTypeTextEdit.setObjectName("fiberTypeTextEdit")
        self.verticalLayout_5.addWidget(self.fiberTypeTextEdit)
        self.otherEquipmentTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.otherEquipmentTextEdit.setFont(font)
        self.otherEquipmentTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.otherEquipmentTextEdit.setObjectName("otherEquipmentTextEdit")
        self.verticalLayout_5.addWidget(self.otherEquipmentTextEdit)
        self.testSettingsLabel = QtWidgets.QLabel(Dialog)
        self.testSettingsLabel.setGeometry(QtCore.QRect(410, 70, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.testSettingsLabel.setFont(font)
        self.testSettingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.testSettingsLabel.setObjectName("testSettingsLabel")
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(400, 100, 191, 261))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.participantNameLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.participantNameLabel.setFont(font)
        self.participantNameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.participantNameLabel.setObjectName("participantNameLabel")
        self.verticalLayout_6.addWidget(self.participantNameLabel)
        self.testTypeLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.testTypeLabel.setFont(font)
        self.testTypeLabel.setObjectName("testTypeLabel")
        self.verticalLayout_6.addWidget(self.testTypeLabel)
        self.testGeometryLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.testGeometryLabel.setFont(font)
        self.testGeometryLabel.setObjectName("testGeometryLabel")
        self.verticalLayout_6.addWidget(self.testGeometryLabel)
        self.testNumberLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.testNumberLabel.setFont(font)
        self.testNumberLabel.setObjectName("testNumberLabel")
        self.verticalLayout_6.addWidget(self.testNumberLabel)
        self.patchLocationLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.patchLocationLabel.setFont(font)
        self.patchLocationLabel.setObjectName("patchLocationLabel")
        self.verticalLayout_6.addWidget(self.patchLocationLabel)
        self.phantomLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.phantomLabel.setFont(font)
        self.phantomLabel.setObjectName("phantomLabel")
        self.verticalLayout_6.addWidget(self.phantomLabel)
        self.solutionLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.solutionLabel.setFont(font)
        self.solutionLabel.setObjectName("solutionLabel")
        self.verticalLayout_6.addWidget(self.solutionLabel)
        self.ROISizeLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ROISizeLabel.setFont(font)
        self.ROISizeLabel.setObjectName("ROISizeLabel")
        self.verticalLayout_6.addWidget(self.ROISizeLabel)
        self.ROIuaLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ROIuaLabel.setFont(font)
        self.ROIuaLabel.setObjectName("ROIuaLabel")
        self.verticalLayout_6.addWidget(self.ROIuaLabel)
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(600, 100, 131, 261))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.participantNameTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.participantNameTextEdit.sizePolicy().hasHeightForWidth())
        self.participantNameTextEdit.setSizePolicy(sizePolicy)
        self.participantNameTextEdit.setObjectName("participantNameTextEdit")
        self.verticalLayout_7.addWidget(self.participantNameTextEdit)
        self.testTypeTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTypeTextEdit.sizePolicy().hasHeightForWidth())
        self.testTypeTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testTypeTextEdit.setFont(font)
        self.testTypeTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.testTypeTextEdit.setObjectName("testTypeTextEdit")
        self.verticalLayout_7.addWidget(self.testTypeTextEdit)
        self.testGeometryTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testGeometryTextEdit.sizePolicy().hasHeightForWidth())
        self.testGeometryTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testGeometryTextEdit.setFont(font)
        self.testGeometryTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.testGeometryTextEdit.setObjectName("testGeometryTextEdit")
        self.verticalLayout_7.addWidget(self.testGeometryTextEdit)
        self.testNumberTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testNumberTextEdit.sizePolicy().hasHeightForWidth())
        self.testNumberTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testNumberTextEdit.setFont(font)
        self.testNumberTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.testNumberTextEdit.setObjectName("testNumberTextEdit")
        self.verticalLayout_7.addWidget(self.testNumberTextEdit)
        self.patchLocationTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.patchLocationTextEdit.setFont(font)
        self.patchLocationTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.patchLocationTextEdit.setObjectName("patchLocationTextEdit")
        self.verticalLayout_7.addWidget(self.patchLocationTextEdit)
        self.phantomTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phantomTextEdit.sizePolicy().hasHeightForWidth())
        self.phantomTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phantomTextEdit.setFont(font)
        self.phantomTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.phantomTextEdit.setObjectName("phantomTextEdit")
        self.verticalLayout_7.addWidget(self.phantomTextEdit)
        self.solutionTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solutionTextEdit.sizePolicy().hasHeightForWidth())
        self.solutionTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.solutionTextEdit.setFont(font)
        self.solutionTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.solutionTextEdit.setObjectName("solutionTextEdit")
        self.verticalLayout_7.addWidget(self.solutionTextEdit)
        self.ROISizeTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROISizeTextEdit.sizePolicy().hasHeightForWidth())
        self.ROISizeTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ROISizeTextEdit.setFont(font)
        self.ROISizeTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ROISizeTextEdit.setObjectName("ROISizeTextEdit")
        self.verticalLayout_7.addWidget(self.ROISizeTextEdit)
        self.ROIuaTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROIuaTextEdit.sizePolicy().hasHeightForWidth())
        self.ROIuaTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ROIuaTextEdit.setFont(font)
        self.ROIuaTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ROIuaTextEdit.setObjectName("ROIuaTextEdit")
        self.verticalLayout_7.addWidget(self.ROIuaTextEdit)
        self.derivedSettingsLabel = QtWidgets.QLabel(Dialog)
        self.derivedSettingsLabel.setGeometry(QtCore.QRect(410, 380, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.derivedSettingsLabel.setFont(font)
        self.derivedSettingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.derivedSettingsLabel.setObjectName("derivedSettingsLabel")
        self.layoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_5.setGeometry(QtCore.QRect(600, 410, 131, 141))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.SPADVoltageTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SPADVoltageTextEdit.setFont(font)
        self.SPADVoltageTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SPADVoltageTextEdit.setObjectName("SPADVoltageTextEdit")
        self.verticalLayout_8.addWidget(self.SPADVoltageTextEdit)
        self.VRSTVoltageTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.VRSTVoltageTextEdit.setFont(font)
        self.VRSTVoltageTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.VRSTVoltageTextEdit.setObjectName("VRSTVoltageTextEdit")
        self.verticalLayout_8.addWidget(self.VRSTVoltageTextEdit)
        self.SubtractorValueTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_5)
        self.SubtractorValueTextEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SubtractorValueTextEdit.setFont(font)
        self.SubtractorValueTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SubtractorValueTextEdit.setReadOnly(True)
        self.SubtractorValueTextEdit.setObjectName("SubtractorValueTextEdit")
        self.verticalLayout_8.addWidget(self.SubtractorValueTextEdit)
        self.subtractorOffsetTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subtractorOffsetTextEdit.setFont(font)
        self.subtractorOffsetTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.subtractorOffsetTextEdit.setReadOnly(False)
        self.subtractorOffsetTextEdit.setObjectName("subtractorOffsetTextEdit")
        self.verticalLayout_8.addWidget(self.subtractorOffsetTextEdit)
        self.delayTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delayTextEdit.setFont(font)
        self.delayTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.delayTextEdit.setReadOnly(True)
        self.delayTextEdit.setObjectName("delayTextEdit")
        self.verticalLayout_8.addWidget(self.delayTextEdit)
        self.layoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_6.setGeometry(QtCore.QRect(400, 410, 191, 141))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.SPADVoltageLabel = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SPADVoltageLabel.setFont(font)
        self.SPADVoltageLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SPADVoltageLabel.setObjectName("SPADVoltageLabel")
        self.verticalLayout_9.addWidget(self.SPADVoltageLabel)
        self.VRSTVoltageLabel = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.VRSTVoltageLabel.setFont(font)
        self.VRSTVoltageLabel.setObjectName("VRSTVoltageLabel")
        self.verticalLayout_9.addWidget(self.VRSTVoltageLabel)
        self.subtractorValueLabel = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.subtractorValueLabel.setFont(font)
        self.subtractorValueLabel.setObjectName("subtractorValueLabel")
        self.verticalLayout_9.addWidget(self.subtractorValueLabel)
        self.subtractorOffsetLabel = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.subtractorOffsetLabel.setFont(font)
        self.subtractorOffsetLabel.setObjectName("subtractorOffsetLabel")
        self.verticalLayout_9.addWidget(self.subtractorOffsetLabel)
        self.delayLabel = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delayLabel.setFont(font)
        self.delayLabel.setObjectName("delayLabel")
        self.verticalLayout_9.addWidget(self.delayLabel)
        self.updateTestSetupButton = QtWidgets.QPushButton(Dialog)
        self.updateTestSetupButton.setGeometry(QtCore.QRect(560, 560, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.updateTestSetupButton.setFont(font)
        self.updateTestSetupButton.setObjectName("updateTestSetupButton")
        self.createTestPatternButton = QtWidgets.QPushButton(Dialog)
        self.createTestPatternButton.setGeometry(QtCore.QRect(380, 560, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.createTestPatternButton.setFont(font)
        self.createTestPatternButton.setObjectName("createTestPatternButton")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 100, 191, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.capturesLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.capturesLabel.setFont(font)
        self.capturesLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.capturesLabel.setObjectName("capturesLabel")
        self.verticalLayout.addWidget(self.capturesLabel)
        self.clkFreqLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clkFreqLabel.setFont(font)
        self.clkFreqLabel.setObjectName("clkFreqLabel")
        self.verticalLayout.addWidget(self.clkFreqLabel)
        self.vcselSettingLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.vcselSettingLabel.setFont(font)
        self.vcselSettingLabel.setObjectName("vcselSettingLabel")
        self.verticalLayout.addWidget(self.vcselSettingLabel)
        self.timeGateLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeGateLabel.setFont(font)
        self.timeGateLabel.setObjectName("timeGateLabel")
        self.verticalLayout.addWidget(self.timeGateLabel)
        self.measPerPattLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.measPerPattLabel.setFont(font)
        self.measPerPattLabel.setObjectName("measPerPattLabel")
        self.verticalLayout.addWidget(self.measPerPattLabel)
        self.pattPerFrameLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pattPerFrameLabel.setFont(font)
        self.pattPerFrameLabel.setObjectName("pattPerFrameLabel")
        self.verticalLayout.addWidget(self.pattPerFrameLabel)
        self.numberOfFramesLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.numberOfFramesLabel.setFont(font)
        self.numberOfFramesLabel.setObjectName("numberOfFramesLabel")
        self.verticalLayout.addWidget(self.numberOfFramesLabel)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(230, 100, 131, 201))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.capturesTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.capturesTextEdit.setFont(font)
        self.capturesTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.capturesTextEdit.setObjectName("capturesTextEdit")
        self.verticalLayout_2.addWidget(self.capturesTextEdit)
        self.clkFreqTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clkFreqTextEdit.setFont(font)
        self.clkFreqTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.clkFreqTextEdit.setObjectName("clkFreqTextEdit")
        self.verticalLayout_2.addWidget(self.clkFreqTextEdit)
        self.VCSELSettingTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.VCSELSettingTextEdit.setFont(font)
        self.VCSELSettingTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.VCSELSettingTextEdit.setObjectName("VCSELSettingTextEdit")
        self.verticalLayout_2.addWidget(self.VCSELSettingTextEdit)
        self.timeGateTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeGateTextEdit.setFont(font)
        self.timeGateTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.timeGateTextEdit.setObjectName("timeGateTextEdit")
        self.verticalLayout_2.addWidget(self.timeGateTextEdit)
        self.measPerPattTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.measPerPattTextEdit.setFont(font)
        self.measPerPattTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.measPerPattTextEdit.setObjectName("measPerPattTextEdit")
        self.verticalLayout_2.addWidget(self.measPerPattTextEdit)
        self.pattPerFrameTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pattPerFrameTextEdit.setFont(font)
        self.pattPerFrameTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pattPerFrameTextEdit.setObjectName("pattPerFrameTextEdit")
        self.verticalLayout_2.addWidget(self.pattPerFrameTextEdit)
        self.numberOfFramesTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numberOfFramesTextEdit.setFont(font)
        self.numberOfFramesTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.numberOfFramesTextEdit.setObjectName("numberOfFramesTextEdit")
        self.verticalLayout_2.addWidget(self.numberOfFramesTextEdit)
        self.loadTestSetupButton = QtWidgets.QPushButton(Dialog)
        self.loadTestSetupButton.setGeometry(QtCore.QRect(560, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loadTestSetupButton.setFont(font)
        self.loadTestSetupButton.setObjectName("loadTestSetupButton")
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 300, 331, 40))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.integrationTimeLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.integrationTimeLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.integrationTimeLabel.setFont(font)
        self.integrationTimeLabel.setObjectName("integrationTimeLabel")
        self.verticalLayout_4.addWidget(self.integrationTimeLabel)
        self.framesPerSecondLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.framesPerSecondLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.framesPerSecondLabel.setFont(font)
        self.framesPerSecondLabel.setObjectName("framesPerSecondLabel")
        self.verticalLayout_4.addWidget(self.framesPerSecondLabel)
        self.loggingEnabledCheckBox = QtWidgets.QCheckBox(Dialog)
        self.loggingEnabledCheckBox.setGeometry(QtCore.QRect(30, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.loggingEnabledCheckBox.setFont(font)
        self.loggingEnabledCheckBox.setObjectName("loggingEnabledCheckBox")
        self.streamModeCheckBox = QtWidgets.QCheckBox(Dialog)
        self.streamModeCheckBox.setGeometry(QtCore.QRect(30, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.streamModeCheckBox.setFont(font)
        self.streamModeCheckBox.setObjectName("streamModeCheckBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Test Setup Window"))
        self.testSetupLabel.setText(_translate("Dialog", "Test Setup"))
        self.conditionsLabel.setText(_translate("Dialog", "Conditions"))
        self.controlSettingsLabel.setText(_translate("Dialog", "Control Settings"))
        self.externalSettingsLabel.setText(_translate("Dialog", "External Settings"))
        self.VCSELBiasLabel.setText(_translate("Dialog", "VCSEL Bias (V)"))
        self.laserWavelengthLabel.setText(_translate("Dialog", "Laser Wavelength (nm)"))
        self.laserPowerLabel.setText(_translate("Dialog", "Laser Power (mW)"))
        self.laserBandwidthLabel.setText(_translate("Dialog", "Laser Bandwidth (nm)"))
        self.fiberTypeLabel.setText(_translate("Dialog", "Fiber Type"))
        self.otherEquipmentLabel.setText(_translate("Dialog", "Other Equipment"))
        self.testSettingsLabel.setText(_translate("Dialog", "Test Settings"))
        self.participantNameLabel.setText(_translate("Dialog", "Participant Name"))
        self.testTypeLabel.setText(_translate("Dialog", "Test Type"))
        self.testGeometryLabel.setText(_translate("Dialog", "Test Geometry"))
        self.testNumberLabel.setText(_translate("Dialog", "Test Number"))
        self.patchLocationLabel.setText(_translate("Dialog", "Patch Location"))
        self.phantomLabel.setText(_translate("Dialog", "Phantom Number"))
        self.solutionLabel.setText(_translate("Dialog", "Solution Number"))
        self.ROISizeLabel.setText(_translate("Dialog", "ROI Size (mm)"))
        self.ROIuaLabel.setText(_translate("Dialog", "ROI uA"))
        self.derivedSettingsLabel.setText(_translate("Dialog", "Constant or Derived Settings"))
        self.SPADVoltageLabel.setText(_translate("Dialog", "SPAD Voltage (V)"))
        self.VRSTVoltageLabel.setText(_translate("Dialog", "VRST Voltage (V)"))
        self.subtractorValueLabel.setText(_translate("Dialog", "Subtractor Value"))
        self.subtractorOffsetLabel.setText(_translate("Dialog", "Subtractor Offset"))
        self.delayLabel.setText(_translate("Dialog", "Delay (ns)"))
        self.updateTestSetupButton.setText(_translate("Dialog", "Update Test Setup"))
        self.createTestPatternButton.setText(_translate("Dialog", "Create Test Pattern"))
        self.capturesLabel.setText(_translate("Dialog", "Number of Captures"))
        self.clkFreqLabel.setText(_translate("Dialog", "Clock Frequency (MHz)"))
        self.vcselSettingLabel.setText(_translate("Dialog", "VCSEL Setting"))
        self.timeGateLabel.setText(_translate("Dialog", "Time Gating Setting"))
        self.measPerPattLabel.setText(_translate("Dialog", "Measurements per Pattern"))
        self.pattPerFrameLabel.setText(_translate("Dialog", "Patterns per Frame"))
        self.numberOfFramesLabel.setText(_translate("Dialog", "Number of Frames"))
        self.loadTestSetupButton.setText(_translate("Dialog", "Load Test Setup"))
        self.integrationTimeLabel.setText(_translate("Dialog", "Integration time is X ms"))
        self.framesPerSecondLabel.setText(_translate("Dialog", "X frames collected per second"))
        self.loggingEnabledCheckBox.setText(_translate("Dialog", "Logging Enabled"))
        self.streamModeCheckBox.setText(_translate("Dialog", "Stream Mode"))
        

    #################################################
    # Configuration done after initialization of ui
    #################################################
    def configure(self):
        
        # Show test values
        self.__show_test_setup_values()
        
        # Connect update button
        self.updateTestSetupButton.clicked.connect(self.__update_test_setup_button_pressed)
        
        # Connect the load button
        self.loadTestSetupButton.clicked.connect(self.__load_test_setup)
        
        # Connect the create test pattern button
        self.createTestPatternButton.clicked.connect(self.__show_emitter_pattern_dialog)
        
        
        
    #################################################
    # Show the values from the data structure in the test setup form 
    #################################################
    def __show_test_setup_values(self):
        
        # Update on-screen values to current data structure values
        self.loggingEnabledCheckBox.setChecked(self.__test_setup.logging)
        self.streamModeCheckBox.setChecked(self.__test_setup.stream_mode)
        self.capturesTextEdit.setPlainText(self.__test_setup.number_of_captures_str)
        self.clkFreqTextEdit.setPlainText(str(round(self.__test_setup.clock_frequency / 1e6, 2)))
        self.VCSELSettingTextEdit.setPlainText(self.__test_setup.vcsel_setting_str)
        self.timeGateTextEdit.setPlainText(self.__test_setup.time_gating_setting_str)
        self.measPerPattTextEdit.setPlainText(self.__test_setup.measurements_per_pattern_str)
        self.pattPerFrameTextEdit.setPlainText(self.__test_setup.patterns_per_frame_str)
        self.numberOfFramesTextEdit.setPlainText(self.__test_setup.number_of_frames_str)
        self.VCSELBiasTextEdit.setPlainText(self.__test_setup.vcsel_bias_str)
        self.laserWavelengthTextEdit.setPlainText(self.__test_setup.laser_wavelength_str)
        self.laserPowerTextEdit.setPlainText(self.__test_setup.laser_power_str)
        self.laserBandwidthTextEdit.setPlainText(self.__test_setup.laser_bandwidth_str)
        self.fiberTypeTextEdit.setPlainText(self.__test_setup.fiber_type_str)
        self.otherEquipmentTextEdit.setPlainText(self.__test_setup.other_equipment_str)
        self.participantNameTextEdit.setPlainText(self.__test_setup.participant_name_str)
        self.testTypeTextEdit.setPlainText(self.__test_setup.test_type_str)
        self.testGeometryTextEdit.setPlainText(self.__test_setup.test_geometry_str)
        self.patchLocationTextEdit.setPlainText(self.__test_setup.patch_location_str)
        self.phantomTextEdit.setPlainText(self.__test_setup.phantom_number_str)
        self.solutionTextEdit.setPlainText(self.__test_setup.solution_number_str)
        self.ROISizeTextEdit.setPlainText(self.__test_setup.roi_size_str)
        self.ROIuaTextEdit.setPlainText(self.__test_setup.roi_ua_str)
        self.SPADVoltageTextEdit.setPlainText(self.__test_setup.spad_voltage_str)
        self.VRSTVoltageTextEdit.setPlainText(self.__test_setup.vrst_voltage_str)
        self.SubtractorValueTextEdit.setPlainText(self.__test_setup.subtractor_value_str)
        self.subtractorOffsetTextEdit.setPlainText(self.__test_setup.subtractor_offset_str)
        self.delayTextEdit.setPlainText(self.__test_setup.delay_str)
        self.conditionsTextEdit.setPlainText(self.__test_setup.conditions_str)
        self.__update_labels()
        
        
    #################################################
    # "Update Test Setup" button handler
    #################################################
    def __update_test_setup_button_pressed(self):
        
        # Update test setup values
        self.__update_test_setup_values()
        
        # Check logging status
        self.__update_logging()
        
        
    #################################################
    # Update the data structure with the values in the test setup form
    #################################################
    def __update_test_setup_values(self):
        self.__test_setup.logging = self.loggingEnabledCheckBox.isChecked()
        self.__test_setup.stream_mode = self.streamModeCheckBox.isChecked()
        self.__test_setup.number_of_captures = self.capturesTextEdit.toPlainText()
        self.__test_setup.clock_frequency = float(self.clkFreqTextEdit.toPlainText()) * 1e6
        self.__test_setup.vcsel_setting = self.VCSELSettingTextEdit.toPlainText()
        self.__test_setup.time_gating_setting = self.timeGateTextEdit.toPlainText()
        self.__test_setup.measurements_per_pattern = self.measPerPattTextEdit.toPlainText()
        self.__test_setup.patterns_per_frame = self.pattPerFrameTextEdit.toPlainText()
        self.__test_setup.number_of_frames = self.numberOfFramesTextEdit.toPlainText()
        self.__test_setup.vcsel_bias = self.VCSELBiasTextEdit.toPlainText()
        self.__test_setup.laser_wavelength = self.laserWavelengthTextEdit.toPlainText()
        self.__test_setup.laser_power = self.laserPowerTextEdit.toPlainText()
        self.__test_setup.laser_bandwidth = self.laserBandwidthTextEdit.toPlainText()
        self.__test_setup.fiber_type = self.fiberTypeTextEdit.toPlainText()
        self.__test_setup.other_equipment = self.otherEquipmentTextEdit.toPlainText()
        self.__test_setup.participant_name = self.participantNameTextEdit.toPlainText()
        self.__test_setup.test_type = self.testTypeTextEdit.toPlainText()
        self.__test_setup.test_geometry = self.testGeometryTextEdit.toPlainText()
        self.__test_setup.patch_location = self.patchLocationTextEdit.toPlainText()
        self.__test_setup.phantom_number = self.phantomTextEdit.toPlainText()
        self.__test_setup.solution_number = self.solutionTextEdit.toPlainText()
        self.__test_setup.roi_size = self.ROISizeTextEdit.toPlainText()
        self.__test_setup.roi_ua = self.ROIuaTextEdit.toPlainText()
        self.__test_setup.spad_voltage = self.SPADVoltageTextEdit.toPlainText()
        self.__test_setup.vrst_voltage = self.VRSTVoltageTextEdit.toPlainText()
        # self.__test_setup.subtractor_value = self.SubtractorValueTextEdit.toPlainText()
        self.__test_setup.subtractor_offset = self.subtractorOffsetTextEdit.toPlainText()
        self.__test_setup.conditions = self.conditionsTextEdit.toPlainText()
        self.__show_test_setup_values()
        
        
    #################################################
    # Update logging
    #################################################
    def __update_logging(self):
        
        # Check to see if logging is enabled
        if self.loggingEnabledCheckBox.isChecked():
            
            # Check to see if logging directory is already set
            if not self.__test_setup.logging_directory_set:
                
                dlg = QtWidgets.QFileDialog()
                dlg.setFileMode(QtWidgets.QFileDialog.Directory)

                # Get filename
                if dlg.exec_():
                    self.__test_setup.logging_directory = dlg.selectedFiles()[0]
                else:
                        print("Logging directory not selected")
                        self.loggingEnabledCheckBox.setChecked(False)
                    
        else:
            
            # Unset logging directory
            self.__test_setup.logging_directory = ""
                    
        #
                        
    # TODO implement when file format is created for loading settings
    def __load_test_setup(self):
        print("This feature is not currently available")
        
        
    #################################################
    # Update information labels showing integration time and captures per second
    #################################################
    def __update_labels(self):
        
        # Calculate integration time
        integration_time = self.__test_setup.number_of_frames * self.__test_setup.measurements_per_pattern * 1.0/(self.__test_setup.clock_frequency)
        
        # Calculate captures per second
        captures_per_second = 1.0 / (integration_time * self.__test_setup.patterns_per_frame )
        
        # Round integration time and convert to ms
        integration_time = round(integration_time*1000, 2)
        
        # Round captures per second
        captures_per_second = round(captures_per_second, 2)
        
        # Update labels
        self.integrationTimeLabel.setText("Integration time is " + str(integration_time) + " ms")
        self.framesPerSecondLabel.setText(str(captures_per_second) + " captures collected per second")
    
        
    #################################################
    # Create emitter pattern window
    #################################################
    def __show_emitter_pattern_dialog(self):
        
        # Update the current test setup values
        self.__update_test_setup_values()
        
        # Update the emitter pattern data structure
        self.__emitter_pattern.update(self.__test_setup.patterns_per_frame)
        
        # Create the emitter pattern window
        self.emitterPatternWindow = Ui_EmitterPatternDialog(self.__emitter_pattern)
        self.emitterPatternDialog = QtWidgets.QDialog()
        self.emitterPatternDialog.setModal(True)
        if self.__test_setup.logo_found:
            self.emitterPatternDialog.setWindowIcon(QtGui.QIcon(self.__test_setup.logo_path))
        self.emitterPatternWindow.setupUi(self.emitterPatternDialog)
        self.emitterPatternWindow.configure()
        self.emitterPatternDialog.show()
        


if __name__ == "__main__":
    import sys
    import TestSetup
    import EmitterPattern
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    test_setup = TestSetup.TestSetup()
    emitter_pattern = EmitterPattern.EmitterPattern()
    ui = Ui_TestSetupDialog(test_setup, emitter_pattern)
    ui.setupUi(Dialog)
    ui.configure()
    Dialog.show()
    sys.exit(app.exec_())

