# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dell-User\Dropbox\MOANA\Python\MOANA3_Python37_Codes\chips\moana3\experiments\gui_development\TestSetupDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(751, 594)
        self.testSetupLabel = QtWidgets.QLabel(Dialog)
        self.testSetupLabel.setGeometry(QtCore.QRect(30, 0, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.testSetupLabel.setFont(font)
        self.testSetupLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.testSetupLabel.setObjectName("testSetupLabel")
        self.conditionsLabel = QtWidgets.QLabel(Dialog)
        self.conditionsLabel.setGeometry(QtCore.QRect(400, 90, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.conditionsLabel.setFont(font)
        self.conditionsLabel.setObjectName("conditionsLabel")
        self.conditionsTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.conditionsTextEdit.setGeometry(QtCore.QRect(480, 90, 261, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.conditionsTextEdit.setFont(font)
        self.conditionsTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.conditionsTextEdit.setCenterOnScroll(True)
        self.conditionsTextEdit.setObjectName("conditionsTextEdit")
        self.controlSettingsLabel = QtWidgets.QLabel(Dialog)
        self.controlSettingsLabel.setGeometry(QtCore.QRect(50, 50, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.controlSettingsLabel.setFont(font)
        self.controlSettingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlSettingsLabel.setObjectName("controlSettingsLabel")
        self.testSettingsLabel = QtWidgets.QLabel(Dialog)
        self.testSettingsLabel.setGeometry(QtCore.QRect(410, 50, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.testSettingsLabel.setFont(font)
        self.testSettingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.testSettingsLabel.setObjectName("testSettingsLabel")
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(400, 120, 191, 151))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.participantNameLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.participantNameLabel.setFont(font)
        self.participantNameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.participantNameLabel.setObjectName("participantNameLabel")
        self.verticalLayout_6.addWidget(self.participantNameLabel)
        self.testTypeLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.testTypeLabel.setFont(font)
        self.testTypeLabel.setObjectName("testTypeLabel")
        self.verticalLayout_6.addWidget(self.testTypeLabel)
        self.deviceIDLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deviceIDLabel.setFont(font)
        self.deviceIDLabel.setObjectName("deviceIDLabel")
        self.verticalLayout_6.addWidget(self.deviceIDLabel)
        self.testNumberLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.testNumberLabel.setFont(font)
        self.testNumberLabel.setObjectName("testNumberLabel")
        self.verticalLayout_6.addWidget(self.testNumberLabel)
        self.patchLocationLabel = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.patchLocationLabel.setFont(font)
        self.patchLocationLabel.setObjectName("patchLocationLabel")
        self.verticalLayout_6.addWidget(self.patchLocationLabel)
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(600, 120, 139, 151))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.participantNameTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.participantNameTextEdit.sizePolicy().hasHeightForWidth())
        self.participantNameTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.participantNameTextEdit.setFont(font)
        self.participantNameTextEdit.setAcceptDrops(True)
        self.participantNameTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.participantNameTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.participantNameTextEdit.setCenterOnScroll(True)
        self.participantNameTextEdit.setObjectName("participantNameTextEdit")
        self.verticalLayout_7.addWidget(self.participantNameTextEdit)
        self.testTypeTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTypeTextEdit.sizePolicy().hasHeightForWidth())
        self.testTypeTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testTypeTextEdit.setFont(font)
        self.testTypeTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.testTypeTextEdit.setCenterOnScroll(True)
        self.testTypeTextEdit.setObjectName("testTypeTextEdit")
        self.verticalLayout_7.addWidget(self.testTypeTextEdit)
        self.deviceIDTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceIDTextEdit.sizePolicy().hasHeightForWidth())
        self.deviceIDTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deviceIDTextEdit.setFont(font)
        self.deviceIDTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.deviceIDTextEdit.setCenterOnScroll(True)
        self.deviceIDTextEdit.setObjectName("deviceIDTextEdit")
        self.verticalLayout_7.addWidget(self.deviceIDTextEdit)
        self.testNumberTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testNumberTextEdit.sizePolicy().hasHeightForWidth())
        self.testNumberTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testNumberTextEdit.setFont(font)
        self.testNumberTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.testNumberTextEdit.setCenterOnScroll(True)
        self.testNumberTextEdit.setObjectName("testNumberTextEdit")
        self.verticalLayout_7.addWidget(self.testNumberTextEdit)
        self.patchLocationTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.patchLocationTextEdit.setFont(font)
        self.patchLocationTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.patchLocationTextEdit.setCenterOnScroll(True)
        self.patchLocationTextEdit.setObjectName("patchLocationTextEdit")
        self.verticalLayout_7.addWidget(self.patchLocationTextEdit)
        self.layoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_5.setGeometry(QtCore.QRect(600, 320, 131, 61))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.SubtractorValueTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_5)
        self.SubtractorValueTextEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SubtractorValueTextEdit.setFont(font)
        self.SubtractorValueTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SubtractorValueTextEdit.setReadOnly(True)
        self.SubtractorValueTextEdit.setObjectName("SubtractorValueTextEdit")
        self.verticalLayout_8.addWidget(self.SubtractorValueTextEdit)
        self.delayTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delayTextEdit.setFont(font)
        self.delayTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.delayTextEdit.setReadOnly(True)
        self.delayTextEdit.setObjectName("delayTextEdit")
        self.verticalLayout_8.addWidget(self.delayTextEdit)
        self.layoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_6.setGeometry(QtCore.QRect(400, 320, 191, 61))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.subtractorValueLabel = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.subtractorValueLabel.setFont(font)
        self.subtractorValueLabel.setObjectName("subtractorValueLabel")
        self.verticalLayout_9.addWidget(self.subtractorValueLabel)
        self.delayLabel = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delayLabel.setFont(font)
        self.delayLabel.setObjectName("delayLabel")
        self.verticalLayout_9.addWidget(self.delayLabel)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 90, 191, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.capturesLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.capturesLabel.setFont(font)
        self.capturesLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.capturesLabel.setObjectName("capturesLabel")
        self.verticalLayout.addWidget(self.capturesLabel)
        self.clkFreqLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clkFreqLabel.setFont(font)
        self.clkFreqLabel.setObjectName("clkFreqLabel")
        self.verticalLayout.addWidget(self.clkFreqLabel)
        self.timeGateLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeGateLabel.setFont(font)
        self.timeGateLabel.setObjectName("timeGateLabel")
        self.verticalLayout.addWidget(self.timeGateLabel)
        self.measPerPattLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.measPerPattLabel.setFont(font)
        self.measPerPattLabel.setObjectName("measPerPattLabel")
        self.verticalLayout.addWidget(self.measPerPattLabel)
        self.pattPerFrameLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pattPerFrameLabel.setFont(font)
        self.pattPerFrameLabel.setObjectName("pattPerFrameLabel")
        self.verticalLayout.addWidget(self.pattPerFrameLabel)
        self.numberOfFramesLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.numberOfFramesLabel.setFont(font)
        self.numberOfFramesLabel.setObjectName("numberOfFramesLabel")
        self.verticalLayout.addWidget(self.numberOfFramesLabel)
        self.NIRVCSELBiasLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NIRVCSELBiasLabel.setFont(font)
        self.NIRVCSELBiasLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.NIRVCSELBiasLabel.setObjectName("NIRVCSELBiasLabel")
        self.verticalLayout.addWidget(self.NIRVCSELBiasLabel)
        self.IRVCSELBiasLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IRVCSELBiasLabel.setFont(font)
        self.IRVCSELBiasLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.IRVCSELBiasLabel.setObjectName("IRVCSELBiasLabel")
        self.verticalLayout.addWidget(self.IRVCSELBiasLabel)
        self.subtractorOffsetLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.subtractorOffsetLabel.setFont(font)
        self.subtractorOffsetLabel.setObjectName("subtractorOffsetLabel")
        self.verticalLayout.addWidget(self.subtractorOffsetLabel)
        self.padCapturedMaskLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.padCapturedMaskLabel.setFont(font)
        self.padCapturedMaskLabel.setObjectName("padCapturedMaskLabel")
        self.verticalLayout.addWidget(self.padCapturedMaskLabel)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(230, 90, 131, 291))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.capturesTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.capturesTextEdit.setFont(font)
        self.capturesTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.capturesTextEdit.setObjectName("capturesTextEdit")
        self.verticalLayout_2.addWidget(self.capturesTextEdit)
        self.clkFreqTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clkFreqTextEdit.setFont(font)
        self.clkFreqTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.clkFreqTextEdit.setObjectName("clkFreqTextEdit")
        self.verticalLayout_2.addWidget(self.clkFreqTextEdit)
        self.timeGateTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeGateTextEdit.setFont(font)
        self.timeGateTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.timeGateTextEdit.setObjectName("timeGateTextEdit")
        self.verticalLayout_2.addWidget(self.timeGateTextEdit)
        self.measPerPattTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.measPerPattTextEdit.setFont(font)
        self.measPerPattTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.measPerPattTextEdit.setObjectName("measPerPattTextEdit")
        self.verticalLayout_2.addWidget(self.measPerPattTextEdit)
        self.pattPerFrameTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pattPerFrameTextEdit.setFont(font)
        self.pattPerFrameTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pattPerFrameTextEdit.setObjectName("pattPerFrameTextEdit")
        self.verticalLayout_2.addWidget(self.pattPerFrameTextEdit)
        self.numberOfFramesTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numberOfFramesTextEdit.setFont(font)
        self.numberOfFramesTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.numberOfFramesTextEdit.setObjectName("numberOfFramesTextEdit")
        self.verticalLayout_2.addWidget(self.numberOfFramesTextEdit)
        self.NIRVCSELBiasTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NIRVCSELBiasTextEdit.setFont(font)
        self.NIRVCSELBiasTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.NIRVCSELBiasTextEdit.setObjectName("NIRVCSELBiasTextEdit")
        self.verticalLayout_2.addWidget(self.NIRVCSELBiasTextEdit)
        self.IRVCSELBiasTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.IRVCSELBiasTextEdit.setFont(font)
        self.IRVCSELBiasTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.IRVCSELBiasTextEdit.setCenterOnScroll(True)
        self.IRVCSELBiasTextEdit.setObjectName("IRVCSELBiasTextEdit")
        self.verticalLayout_2.addWidget(self.IRVCSELBiasTextEdit)
        self.subtractorOffsetTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subtractorOffsetTextEdit.setFont(font)
        self.subtractorOffsetTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.subtractorOffsetTextEdit.setReadOnly(False)
        self.subtractorOffsetTextEdit.setCenterOnScroll(True)
        self.subtractorOffsetTextEdit.setObjectName("subtractorOffsetTextEdit")
        self.verticalLayout_2.addWidget(self.subtractorOffsetTextEdit)
        self.padCapturedMaskTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.padCapturedMaskTextEdit.setFont(font)
        self.padCapturedMaskTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.padCapturedMaskTextEdit.setReadOnly(False)
        self.padCapturedMaskTextEdit.setCenterOnScroll(True)
        self.padCapturedMaskTextEdit.setObjectName("padCapturedMaskTextEdit")
        self.verticalLayout_2.addWidget(self.padCapturedMaskTextEdit)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 390, 331, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.integrationTimeLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.integrationTimeLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.integrationTimeLabel.setFont(font)
        self.integrationTimeLabel.setObjectName("integrationTimeLabel")
        self.verticalLayout_4.addWidget(self.integrationTimeLabel)
        self.framesPerSecondLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.framesPerSecondLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.framesPerSecondLabel.setFont(font)
        self.framesPerSecondLabel.setObjectName("framesPerSecondLabel")
        self.verticalLayout_4.addWidget(self.framesPerSecondLabel)
        self.loggingEnabledCheckBox = QtWidgets.QCheckBox(Dialog)
        self.loggingEnabledCheckBox.setGeometry(QtCore.QRect(30, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.loggingEnabledCheckBox.setFont(font)
        self.loggingEnabledCheckBox.setObjectName("loggingEnabledCheckBox")
        self.derivedSettingsLabel = QtWidgets.QLabel(Dialog)
        self.derivedSettingsLabel.setGeometry(QtCore.QRect(410, 280, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.derivedSettingsLabel.setFont(font)
        self.derivedSettingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.derivedSettingsLabel.setObjectName("derivedSettingsLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 450, 701, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadTestSetupButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loadTestSetupButton.setFont(font)
        self.loadTestSetupButton.setObjectName("loadTestSetupButton")
        self.horizontalLayout.addWidget(self.loadTestSetupButton)
        self.loadDynamicPatternButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loadDynamicPatternButton.setFont(font)
        self.loadDynamicPatternButton.setObjectName("loadDynamicPatternButton")
        self.horizontalLayout.addWidget(self.loadDynamicPatternButton)
        self.loadYieldButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loadYieldButton.setFont(font)
        self.loadYieldButton.setObjectName("loadYieldButton")
        self.horizontalLayout.addWidget(self.loadYieldButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(500, 550, 231, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.updateTestSetupButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.updateTestSetupButton.setFont(font)
        self.updateTestSetupButton.setObjectName("updateTestSetupButton")
        self.horizontalLayout_2.addWidget(self.updateTestSetupButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 490, 701, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.editTestSetupButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editTestSetupButton.setFont(font)
        self.editTestSetupButton.setObjectName("editTestSetupButton")
        self.horizontalLayout_4.addWidget(self.editTestSetupButton)
        self.verifyDynamicPacketButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.verifyDynamicPacketButton.setFont(font)
        self.verifyDynamicPacketButton.setObjectName("verifyDynamicPacketButton")
        self.horizontalLayout_4.addWidget(self.verifyDynamicPacketButton)
        self.editYieldButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editYieldButton.setFont(font)
        self.editYieldButton.setObjectName("editYieldButton")
        self.horizontalLayout_4.addWidget(self.editYieldButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.testSetupLabel.setText(_translate("Dialog", "Test Setup"))
        self.conditionsLabel.setText(_translate("Dialog", "Conditions"))
        self.controlSettingsLabel.setText(_translate("Dialog", "Control Settings"))
        self.testSettingsLabel.setText(_translate("Dialog", "Test Settings"))
        self.participantNameLabel.setText(_translate("Dialog", "Participant Name"))
        self.testTypeLabel.setText(_translate("Dialog", "Test Type"))
        self.deviceIDLabel.setText(_translate("Dialog", "Device ID"))
        self.testNumberLabel.setText(_translate("Dialog", "Test Number"))
        self.patchLocationLabel.setText(_translate("Dialog", "Patch Location"))
        self.subtractorValueLabel.setText(_translate("Dialog", "Subtractor Value"))
        self.delayLabel.setText(_translate("Dialog", "Delay (ns)"))
        self.capturesLabel.setText(_translate("Dialog", "Number of Captures"))
        self.clkFreqLabel.setText(_translate("Dialog", "Clock Frequency (MHz)"))
        self.timeGateLabel.setText(_translate("Dialog", "Time Gating Setting"))
        self.measPerPattLabel.setText(_translate("Dialog", "Measurements per Pattern"))
        self.pattPerFrameLabel.setText(_translate("Dialog", "Patterns per Frame"))
        self.numberOfFramesLabel.setText(_translate("Dialog", "Number of Frames"))
        self.NIRVCSELBiasLabel.setText(_translate("Dialog", "NIR VCSEL Bias (V)"))
        self.IRVCSELBiasLabel.setText(_translate("Dialog", "IR VCSEL Bias (V)"))
        self.subtractorOffsetLabel.setText(_translate("Dialog", "Subtractor Offset"))
        self.padCapturedMaskLabel.setText(_translate("Dialog", "Pad Captured Mask"))
        self.integrationTimeLabel.setText(_translate("Dialog", "Integration time is X ms"))
        self.framesPerSecondLabel.setText(_translate("Dialog", "X frames collected per second"))
        self.loggingEnabledCheckBox.setText(_translate("Dialog", "Logging Enabled"))
        self.derivedSettingsLabel.setText(_translate("Dialog", "Derived Settings"))
        self.loadTestSetupButton.setText(_translate("Dialog", "Load Test Setup"))
        self.loadDynamicPatternButton.setText(_translate("Dialog", "Load Dynamic Packet"))
        self.loadYieldButton.setText(_translate("Dialog", "Load Yield"))
        self.updateTestSetupButton.setText(_translate("Dialog", "Update"))
        self.editTestSetupButton.setText(_translate("Dialog", "Direct Edit Test Setup"))
        self.verifyDynamicPacketButton.setText(_translate("Dialog", "Verify Dynamic Packet"))
        self.editYieldButton.setText(_translate("Dialog", "Direct Edit Yield"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

